### ISSUE TITLE
Error on using mingle inside nested Components

### ISSUE THREAD

**Issue by renky** [ijpatricio/mingle#37]
Hi @ijpatricio 

still using your great package and indeed in more and more complex situations
 
Currently I try to use wire-elements/modal package to load livewire-components inside a page-modal dialog. Btw.. another great package:
https://github.com/wire-elements/modal

in my situation i now try to load a mingle inside such a dialog, and now opening up the dialog, i run into an error

```
Alpine Expression Error: Cannot read properties of undefined (reading 'Elements')

Expression: "
        window.Mingle.Elements['resources/js/mingles/ImageEditor/ImageEditor.js']
            .boot(
                'mingle-8pETZDDEP3JJDXRz',
                '8ZcNRUaoUWhHF4MKXieP',
            )
    "
```

I also already dived into it and indeed it is because my component isn't correct registered inside window.mingle.Elements. This seems to be because inside the Dialog-Component - which is a nesting of components - the mingle.stack-script isn't called
```
@push(config('mingle.stack'))
    @vite($this->component())
@endpush
````

and indeed I can solve this issue, by just doing that manually.
- when i add this code to my parent component that is loaded on page-load
```
@push(config('mingle.stack'))
    @vite('resources/js/mingles/ImageEditor/ImageEditor.js')
@endpus
````
it works perfectly fine...

so now the question is: do you have any idea how to solve that automatically? Livewire seems just to ignore this script-loading-information on loading the nested component

**Comment by ijpatricio** [comment]
Hmm there is a way for sure, loading such a script in deferred, just when the modal opens.

The easy fix is like you did, pre-loading manually on the parent.

Potentially, in a future, I can add such thing.

The current situation is that I don't want to add more features until I finish the environment setup.

I want to have the playground ready, php tests, e2e tests, all of that in the package, before adding more and more stuff.

I will do that for sure, it just will take some time, as I'm working on this alone, in my free time, which hasn't been much lately :)

Your feedback has been amazing, the support replying to other issues as well, much appreciated ❤ thank you @renky

**Comment by ijpatricio** [comment]
I added the reference in #12 to revisit this, and add async loading. Thanks!

**Comment by renky** [comment]
to be honest: i guess this one is solved already with the mingle-Blade-directive
I just saw it today but hadn't a chance to make the update in the project and trying to remove the calls... I guess it will solve the issue...

**Comment by renky** [comment]
@ijpatricio sorry for wrong information -> indeed it was not yet solved by the @mingle directive - without testing i thought you always load all mingles...

nevertheless - I think it shouldn't be that complex - since x-init is always called, when a mingle is included, I thought about just adding the script-loading-logic to the x-init function.... finally that solution also gets rid of the @mingle-directive, because it always loads the mingle js on demand...

```
// mingle.blade.php

<div
    x-data="{
        bootMingle() {
            window.Mingle.Elements['{{ $this->component() }}']
                .boot(
                    '{{ $this->mingleId }}',
                    '{{ $_instance->getId() }}',
                )
        },
        init() {
            if (window.Mingle && window.Mingle.Elements && window.Mingle.Elements['{{ $this->component() }}']) {
                this.bootMingle();

                return;
            }

            const scriptUrl = '{{ \Illuminate\Support\Facades\Vite::asset($this->component()) }}';
            const scriptEl = document.querySelector(`script[src='`+ scriptUrl + `']`);

            if (! scriptEl) {
                // Mingle not loaded already
                const script = document.createElement('script');
                script.src = scriptUrl;
                script.defer = true;
                script.type = 'module';
                script.onload = () => {
                    this.bootMingle();
                };
                document.head.appendChild(script);

                return;
            }

            // Script already attached, but mingle not loaded - so wait a bit
            const interval = setInterval(() => {
                if (window.Mingle && window.Mingle.Elements && window.Mingle.Elements['{{ $this->component() }}']) {
                    clearInterval(interval);
                    this.bootMingle();
                }
            }, 50);
        },
    }"
>
    <div id="{{ $this->mingleId }}-container" wire:ignore x-ignore>
        <div
                id="{{ $this->mingleId }}"
                data-mingle-data="{{ json_encode($this->mingleData()) }}"
        ></div>
    </div>
</div>

```

I'm not sure if it is the definitive answer and I think it is not the ultimate wisdom for all our cases, but it works in my environment...

what i don't like about that solution is that huge js-code that gets loaded repeatedly for each mingle... creating an alpine-component for it would be a solution - but to load it into alpine everybody would have to add livewire-scripts with an own app.js... so it's not really good - as far as there is no solution how we could inject an alpine component into that alpine solution that is started by livewire i don't know how to make it simpler... It would be great, if we would be able to reduce it to a simple x-data="mingle('{{ $this->component() }}')"
and all this stuff would be done inside an alpine-component...

**Comment by denizaygundev** [comment]
@renky @ijpatricio sorry to also add to this issue but I'm encountering the same problem, where I'm wanting to use another package but it fails before I can even resolve the import `import { CalProvider } from '@calcom/atoms';` from my `.jsx` because of 
```Uncaught TypeError: Cannot read properties of undefined (reading 'Elements')
    at [Alpine] 
        window.Mingle.Elements['resources/js/cal-atom/index.js']```

**Comment by renky** [comment]
@denizaygundev Well I think the problem is completely independent from external libraries - i just thing due to the occurance of a JS-Error other js-code isn't executed... so you have to get rid of the JS error caused by mingle, and then your external lbi should work...

as i just figured out in my last comment: the @mingles directive doesn't load all mingles automatically - it just injects the mingles, that are know at time of the initial request - each Livewire-Mingle-Component is registering itself in the MinglesService and the directive takes it out of the service and adds the script tag... 

For Mingles that are loaded asynchronous by running a livewire-action (and filament is doing a lot of that) the script is just missing in the DOM and because of that you get this error...

So you have now two options:

1. Take care about all scripts loaded in your page, that you need... you can achieve that by replacing the automatic @mingles directive and just add all mingle-js-files manually to your layout-blade-file - maybe like this
```
@vite(['resources/js/MyMingle1.js', 'resources/js/MyMingle2.js', ...])
```
The downside of this, that your page loads ALL Mingles on pageload, even if you don't need it for the current use - but on the other hand - all mingles will be there and work fine

2. Take my solution from the comment above - just publish the views of the MIngle Package and replace the content of the mingle.blade.php with my code above - that code should work and load all your mingles exactly when it is used for the first time independend if it is loaded with the page or asynchronous.
The downside of this is as I mentioned: the huge JS-Code that is loaded over and over again - but maybe we find a solution to make it smalle - I just figured out, that it is possible to register new Alpine-Components after Alpine was already started - so maybe we can inject this code into a Livewire-init-Hook

**Comment by denizaygundev** [comment]
@renky I appreciate you getting back to me! 

I've actually applied @ijpatricio 's latest recommendation of auto-registering the scripts as seen [here](https://minglejs.unitedbycode.com/auto-import-on-build) but this still doesn't help with 3rd party JS

In the exact same file that works fine `Counter.jsx`, but the moment I try to import `import { CalProvider } from '@calcom/atoms';`, I get
```
livewire.js?id=38dc8241:1124 Uncaught TypeError: Cannot read properties of undefined (reading 'Elements')
    at [Alpine] 
        window.Mingle.Elements['resources/js/cal-atom/index.js']
            .boot(
```

Maybe I'm missing something very obvious

**Comment by renky** [comment]
@denizaygundev As I just mentioned in my comment above:
the auto-registering and auto-loading only cares about the Mingels that are loaded together with the initial browser-request for the page - If you add a mingle to the DOM by just calling a livewire-action/reload/rendering (what filament and other livewire pages do), that was not already there on Browser-Request, then you run into this error... 

So it must be loaded on demand (my solution 2 like I do it in my project since yesterday) or you have to care about that all mingles are loaded on initial page-load (manually registering - as I did it until yesterday - my solution 1).

**Comment by fikri-kompanion** [comment]
Just happen to have this problem and saw this thread is active right now. I did some hack to always include mingles on every page load, but it still not rendering. The hack need to extend original `Mingle.php` and `Vite.php`. Even with including every js on every page, it didn't render, but did not throw any error. Is there a way to force it to render/rerender?

```php
public function mingleScripts(): string
{
    $mingles = [];

    $vite = app(ExtendedVite::class)->useHotFile($this->hotFile())->useBuildDirectory($this->buildDirectory);

    foreach ($vite->getManifests() as $file => $manifest) {
        if (Str::startsWith($file, 'resources/js/Mingles')) {
            $mingles[] = $file;
        }
    }

    return collect($mingles)
        ->unique()
        ->map(function ($mingle) use ($vite) {
            return $vite->withEntryPoints($mingle)->toHtml();
        })
        ->pipe($this->addReactPreambleToTheTop(...))
        ->implode(PHP_EOL) . PHP_EOL;
}
```

**Comment by denizaygundev** [comment]
@renky sorry I misunderstood that - I've now published the mingle blade and using your solution 2 for on-demand loading 

Which looked promising for a second as I saw: 

```
9:03:45 AM [vite] hmr update /resources/js/cal-atom/Counter.jsx
9:03:46 AM [vite] ✨ new dependencies optimized: @calcom/atoms
9:03:46 AM [vite] ✨ optimized dependencies changed. reloading
```

But now I just get a  `Uncaught TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`

I wonder if anyone has gotten 3rd party JS packages to load in

**Comment by renky** [comment]
I think you use Vue? Just publish the mingle.config and disable the setting for activating the react_preamble_enabled - per default it is activated - I also ran in to that issue

**Comment by renky** [comment]
@fikri-kompanion I think this is a different issue - your hack seems to make sense to me - you can just add debugger-commands to your mingle-js-files to see if it is really added... 

finally you can also add debugger-entries to your Vue/React files and see if it gets executed - and if it gets, then I guess the issue is inside the Mingle

**Comment by denizaygundev** [comment]
I'm using React, this package only supports react as of now @renky

**Comment by fikri-kompanion** [comment]
owh wait. my hack did work. turn out im just stupid. @renky

**Comment by renky** [comment]
@denizaygundev ok - i'm not using React right now - so don't have a clue about what this ReactCurrentDispatcher is, what the react_preamble-enabled really does and if it is necessary... I can only say: I saw the same error on my Vue-Mingle and deactivating the preamble solved the issue... maybe you just miss any NPM-Package - maybe @ijpatricio can help you about that
But finally I'm quite sure, that it has nothing to do with the external package

**Comment by denizaygundev** [comment]
@renky no problem at all, I'll keep chipping away at it - thank you so much for your help!

**Comment by denizaygundev** [comment]
I've managed to get it working roughly with the [mingle-demo](https://github.com/ijpatricio/minglejs-demo) project so it must be a livewire/filament issue specifically

**Comment by ijpatricio** [comment]
Hey guys!

So it worked, right??

Did you see this page @denizaygundev ?? https://minglejs.unitedbycode.com/filament-and-react

**Comment by ijpatricio** [comment]
@renky react preamble is related to the Hot Module Replacement - live reload.

@denizaygundev if this helps https://github.com/ijpatricio/rubberduck

A project where I actually have React 19 and Vue 3 on the same page. And use stores - Zustand and Pinia, while subscribing updates

Can you make a reproduction repository? It would make it easier for us to debug

**Comment by denizaygundev** [comment]
@ijpatricio yes of course, I've gone through all of your docs and issues multiple times :) 

I got it work by setting it up in your demo first, it looks like my own project wasn't working because it uses react19 instead of react18

**Comment by ijpatricio** [comment]
Aaaah ok ok! I got React19 with Mingle already, so I got confused for a bit :)

All good then, awesome!! 🎉

**Comment by renky** [comment]
hey guys - thanks to livewire this is all much more easy!!!
we can just use @assets-directive. Finally livewire cares about adding the scripts to the DOM...
i opened up a pull request @ijpatricio :
https://github.com/ijpatricio/mingle/pull/45
this also makes the mingles directive unnecessary!!
